config/routes.rb
VeganTuesdays::Application.routes.draw do
  
  resources :posts do
    resources :comments
  end

  get "home/index"

  root :to => "home#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :email, :name, :post_id
  has_many :comments, :dependent => :destroy
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :subtitle, :title
  validates_presence_of :title, :content
  validates_uniqueness_of :title
  has_many :comments, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
  @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params[:comment])
    respond_to do |format|
      if @comment.save
        format.html { redirect_to(@post, :notice => 'Comment was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { redirect_to(@post, :notice => 
        'Comment could not be saved. Please fill in all fields')}
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
  <p>
    <b>Name:</b>
    <%= comment.name %>
  </p>
 
  <p>
    <b>Comment:</b>
    <%= comment.body %>
  </p>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Post</th>
    <th>Name</th>
    <th>Email</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.post_id %></td>
    <td><%= comment.name %></td>
    <td><%= comment.email %></td>
    <td><%= comment.body %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Post:</b>
  <%= @comment.post_id %>
</p>

<p>
  <b>Name:</b>
  <%= @comment.name %>
</p>

<p>
  <b>Email:</b>
  <%= @comment.email %>
</p>

<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/home/index.html.erb
		<div class="entryWrap">
			<div class="entryHead clearfix">
				<div class="entryTitle">coconut lentil soup</div>
				<div class="entryDate">tuesday february 5, 2013</div>
				<div class="subTitle">from amy's awesome vegan book</div>
			</div>
			<div class="landscape"><img src="assets/landscapeSoup1.jpg"></div>
			<p>Veggies sunt bona vobis, proinde vos postulo esse magis mustard celery epazote turnip lotus root courgette beetroot quandong garlic amaranth horseradish cress earthnut pea taro.
			<br />
			<br />
			Leek garlic yarrow chicory lentil chickweed. Yarrow broccoli daikon salsify tomatillo celtuce chicory water chestnut spinach welsh onion green bean. Rutabaga arugula bitterleaf chicory fennel burdock gram cauliflower nori pea sprouts kakadu plum bok choy celtuce mustard winter purslane zucchini spring onion rutabaga.</p>
			<div class="portrait"><img src="assets/portraitSoup.jpg"></div>
			<p>Mustard asparagus water spinach okra celtuce garlic melon brussels sprout pea sprouts chickweed kakadu plum watercress. Endive squash jícama nori sea lettuce tatsoi asparagus ricebean groundnut bush tomato bunya nuts kombu garbanzo salsify melon leek. Plantain soybean daikon courgette leek zucchini bamboo shoot fava bean celtuce lentil tigernut.
			<br />
			<br />
			Earthnut pea endive cucumber water chestnut winter purslane taro daikon tomato celery sweet pepper napa cabbage kale cress sierra leone bologi radicchio nori ricebean earthnut pea. Rock melon groundnut horseradish cabbage melon chickpea chicory peanut seakale. Shallot broccoli soko celtuce taro okra dulse horseradish cress sierra leone bologi corn welsh onion cabbage mung bean.</p>
			<div class="landscape"><img src="assets/landscapeSoup2.jpg"></div>
			<p>Collard greens melon plantain water spinach lotus root pumpkin asparagus napa cabbage arugula bell pepper groundnut bitterleaf. Avocado jícama sweet pepper kombu leek komatsuna caulie broccoli rutabaga avocado fava bean pea earthnut pea rock melon. Wakame okra tomato carrot seakale komatsuna.
			<br />
			<br />
			Beetroot fava bean artichoke groundnut endive tomato onion carrot avocado broccoli winter purslane pea chicory courgette salsify taro. Groundnut mustard celery horseradish soybean cress fennel beet greens radish gumbo caulie parsnip sweet pepper kakadu plum burdock celery. Garlic shallot spinach arugula garbanzo collard greens parsnip azuki bean groundnut okra. Azuki bean catsear potato bush tomato black-eyed pea watercress prairie turnip. Carrot mung bean coriander sweet pepper summer purslane maize horseradish caulie corn grape collard greens.</p>
						
			<!-- RECIPE CARD -->
						
			<div class="recipeCard clearfix">
				<div class="topCard clearfix">
					<div class="cardImg"><img src="assets/cardSoup.jpg"></div>
					<div class="titleServings">
						<div class="cardTitle">coconut lentil soup</div>
						<div class="servings">serves 6</div>
					</div>
					<div class="cardNotes">
						<p>Notes.</p>
						<p>Notessss. Short and sweet. This recipe was delicious and we cannot wait to make it again. Next time- less ginger.</p>
					</div>
				</div>
				<div class="cardLeft">
					<h2>Ingredients</h2>
					<ul>
						<li>coconut milk</li>
						<li>vegetable broth</li>
						<li>onions; chopped</li>
						<li>lentils</li>
						<li>buttloads of ginger</li>
					</ul>
					<h3>Separated ingredients</h3>
					<ul>
						<li>cumin</li>
						<li>salt</li>
						<li>pepper</li>
						<li>cayenne</li>
					</ul>
				</div>
				<div class="cardRight">
					<h2>Instructions</h2>
					<p>Step one.</p>
					<p>Step two.</p>
					<p>Step three.</p>
					<p>Step quatro.</p>
					<p>Step cinco.</p>
					<p>Step six.</p>
					<p class="nutrition">Optional Info. (Nutrition Facts)</p>
					<div class="print"></div>
					<div class="save"></div>
				</div>
			</div> <!-- Recipe Card -->
			<div class="endEntry"><img src="assets/endcap.png"</div>
		</div> <!--Entry Wrap -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VeganTuesdays</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div id="container">

		<div id="header"><a class="logo" href="#">Vegan Tuesdays</a></div>
		<div id="nav">               
			<div class="nav"> <%= link_to "Home", posts_path %></div>
			<div class="nav"> <a href="#">Recipes</a></div>
			<div class="nav"> <a href="#">About</a></div>
		</div>
		<div id="content">

			<%= yield %>

		</div>
	</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subtitle %><br />
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Subtitle:</b>
  <%= @post.subtitle %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
<%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Subtitle</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.subtitle %></td>
    <td><%= post.content %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, :confirm => 'Are you sure?',
                                     :method => :delete %></td>
  </tr>
<% end %>
</table>
 
<br />
 
<%= link_to 'New post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Subtitle:</b>
  <%= @post.subtitle %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>

<h2>Comments</h2>
<%= render @post.comments %>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<h2>Add a comment:</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
  	<%= f.label :email %><br />
  	<%= f.text_field :email %><br />
  </div>	
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
 
<%= link_to 'Edit Post', edit_post_path(@post) %> |
<%= link_to 'Back to Posts', posts_path %> |